"""Cambiamos id a UUID

Revision ID: c75df8665744
Revises: 67e287699eb0
Create Date: 2025-09-11 20:55:49.262373

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             


# revision identifiers, used by Alembic.
revision = 'c75df8665744'
down_revision = '67e287699eb0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###